### ISSUE TITLE
Existing value attributes are removed.

### ISSUE THREAD

**Issue by arigoldx** [hacklanta/lift-formality#2]
Here's m'html:

```
<input type="number" name="repeat" min="0" value="0">
```

and here's m'code:

```
field[Int]("name=repeat"),
```

The resulting html has no `value` attribute.

**Comment by Shadowfiend** [comment]
I think we can probably take [this bit of the `baseFieldTransform`](https://github.com/hacklanta/lift-formality/blob/master/src/main/scala/com/hacklanta/formality/FieldHandling.scala#L163) and make it so that if we're `Empty` we don't add that transformation at all, so the `value` attribute remains unchanged in those cases. Should be pretty easy.
