### ISSUE TITLE
If a field is left blank, onSuccess isn't called.

### ISSUE THREAD

**Issue by arigoldx** [hacklanta/lift-formality#6]
Essentially, if a value isn't entered for a field, that field isn't validated and `onSuccess` isn't called.

On the one hand, `onSuccess` sounds like it should be what's called when all fields have been validated. Maybe `onFailure` should be the handler for when fields are left blank. However, that doesn't work. The problem, I think, is that since the field's validators aren't called, the failure has no data identifying it:

```
Failure(Empty,Empty,Empty)
```

and therefore we can't handle that field in `onFailure`.

**Comment by Shadowfiend** [comment]
So really this is a two-part piece:
- We should probably call `onFailure` with something clearer than just empties all around when a form element is not submitted at all (e.g., as with a select box with no selection).
- We should allow for validating a field that has no value (i.e., allow for validations that take `Box[T]`), so that the above can register as an empty value and fail validation.

Will look into this some more… I suspect there are some complications to be found, especially in the second bit.

**Comment by Shadowfiend** [comment]
Yes, validating a field with no value gets interesting because that field's handler is never invoked.

Fortunately we've got grouping mechanisms in the form and in the field group that let us check for empties and force them through an extra validation step. I think that's what I'll do.

**Comment by riveramj** [comment]
This can prob be closed due to #9 but will let @Shadowfiend close it since he was involved.

**Comment by Shadowfiend** [comment]
Yeeeep, right you are!
